services:
  airsonic:
    image: lscr.io/linuxserver/airsonic
    container_name: airsonic
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERCONFDIR}/airsonic:/config
      - ${DOCKERSTORAGEDIR}/media/music:/music
      - ${DOCKERSTORAGEDIR}/media/playlists:/playlists
      - ${DOCKERSTORAGEDIR}/media/podcasts:/podcasts
      - ${DOCKERSTORAGEDIR}/media:/media #optional
    ports:
      - 4040:4040
    devices:
      - /dev/snd:/dev/snd #optional
    restart: unless-stopped