services:
  # Plex - Media Server
  plex:
    image: plexinc/pms-docker:public
    container_name: plex
    restart: unless-stopped
    networks:
      - default
    ports:
      - "32400:32400/tcp"
      # - "3005:3005/tcp"
      # - "8324:8324/tcp"
      # - "32469:32469/tcp"
      # - "1900:1900/udp"
      # - "32410:32410/udp"
      # - "32412:32412/udp"
      # - "32413:32413/udp"
      # - "32414:32414/udp"
      # - "33400:33400" # If you use Plex Web Tools
    # devices:
    #   - /dev/dri:/dev/dri # for hardware transcoding
    volumes:
      - ${DOCKERCONFDIR}/plex:/config
      - ${DOCKERSTORAGEDIR}/media:/data/media
    environment:
      TZ: $TZ
      HOSTNAME: "dockerPlex"
      PLEX_CLAIM: $PLEX_CLAIM_TOKEN
      PLEX_UID: $PUID
      PLEX_GID: $PGID
      ADVERTISE_IP: $PLEX_ADVERTISE_URL
      ALLOWED_NETWORKS: $LAN_NETWORK



      
      