services:
# Lidarr
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      #- UMASK_SET=022 #optional
    volumes:
      - ${DOCKERCONFDIR}/overseerr:/config
      - ${DOCKERSTORAGEDIR}:/data
    ports:
      - 8686:8686
    restart: unless-stopped